# Generated by Django 5.0.2 on 2024-02-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('object', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('admin', models.BooleanField()),
                ('photo', models.CharField(max_length=255)),
            ],
        ),
    ]
